const sampleMatchData = {
  homeTeam: {
    name: "TFL HOME",
    formation: "4-2-3-1",
    color: "home",
  },
  awayTeam: {
    name: "TFL AWAY",
    formation: "4-3-3",
    color: "away",
  },
  status: "LIVE",
  substitutionsLeft: 3,
};

const samplePlayers = [
  { id: "home-gk", team: "home", number: 1, label: "GK-1", position: "GK", stamina: 91, condition: "A", status: "정상", focus: 90, formation: [50, 90] },
  { id: "home-cb4", team: "home", number: 4, label: "CB-4", position: "CB", stamina: 83, condition: "B", status: "정상", focus: 88, formation: [38, 76] },
  { id: "home-dm6", team: "home", number: 6, label: "DM-6", position: "DM", stamina: 51, condition: "C", status: "부상 위험", focus: 66, formation: [42, 58] },
  { id: "home-am10", team: "home", number: 10, label: "AM-10", position: "AM", stamina: 74, condition: "A", status: "경고 1", focus: 79, formation: [50, 38] },
  { id: "home-st9", team: "home", number: 9, label: "ST-9", position: "ST", stamina: 68, condition: "B", status: "정상", focus: 82, formation: [50, 18] },
  { id: "home-wm7", team: "home", number: 7, label: "WM-7", position: "WM", stamina: 72, condition: "B", status: "정상", focus: 76, formation: [24, 40] },
  { id: "away-gk", team: "away", number: 1, label: "GK-1", position: "GK", stamina: 88, condition: "A", status: "정상", focus: 87, formation: [50, 10] },
  { id: "away-cb5", team: "away", number: 5, label: "CB-5", position: "CB", stamina: 79, condition: "B", status: "정상", focus: 81, formation: [58, 26] },
  { id: "away-fb3", team: "away", number: 3, label: "FB-3", position: "FB", stamina: 63, condition: "C", status: "압박 대응", focus: 70, formation: [74, 30] },
  { id: "away-dm8", team: "away", number: 8, label: "DM-8", position: "DM", stamina: 76, condition: "B", status: "정상", focus: 77, formation: [58, 46] },
];

const sampleBenchPlayers = [
  { id: "bench-12", number: 12, label: "B-12", position: "ST", stamina: 96, condition: "B", status: "공격 옵션" },
  { id: "bench-08", number: 8, label: "B-08", position: "CM", stamina: 92, condition: "A", status: "교체 후보" },
  { id: "bench-21", number: 21, label: "B-21", position: "FB", stamina: 89, condition: "B", status: "부상 위험 낮음" },
  { id: "bench-04", number: 4, label: "B-04", position: "CB", stamina: 87, condition: "B", status: "수비 안정" },
];

const sampleEvents = [
  {
    id: "dribble",
    type: "드리블",
    badge: "DRIBBLE",
    time: "63:30",
    clock: "후반 63:30",
    score: [1, 1],
    subtitle: "공은 바둑알 바깥 발밑, 모든 바둑알은 짧게 동시 이동",
    commentary: "AM-10이 공을 바깥 발밑에 두고 부드럽게 전진합니다. 압박 수비와 패스 후보도 함께 위치를 잡습니다.",
    routePath: "M51.6 29.5 C52.6 29.3 53.7 29.1 54.7 29.0",
    ballFrom: [51.6, 52.6],
    ballTo: [54.7, 51.8],
    motion: {
      kind: "carry",
      touch: [52.8, 52.2],
      mid: [53.5, 52.4],
      duration: 1240,
      ease: "cubic-bezier(0.2, 0.74, 0.22, 1)",
      scale: 1.02,
    },
    actors: [
      { playerId: "home-am10", role: "공 소유", x: 51.8, y: 50.7, from: [48.8, 51.4], core: true, cardAnchor: "top", duration: 1240 },
      { playerId: "away-dm8", role: "압박 수비", x: 56.4, y: 47.6, from: [55.8, 49.6], core: false, duration: 1240 },
      { playerId: "home-st9", role: "패스 후보", x: 63.0, y: 42.8, from: [61.2, 43.5], option: true, duration: 1240 },
      { playerId: "home-wm7", role: "패스 후보", x: 49.0, y: 66.8, from: [47.4, 68.6], option: true, duration: 1240 },
    ],
  },
  {
    id: "tackle",
    type: "태클",
    badge: "TACKLE",
    time: "66:00",
    clock: "후반 66:00",
    score: [1, 1],
    subtitle: "태클 성공: 접근 경합 후 공 소유권이 수비수 발밑으로 이동",
    commentary: "DM-8이 겹치지 않는 거리에서 태클에 성공합니다. 공은 AM-10 안쪽이 아니라 DM-8의 바깥 발밑으로 이동합니다.",
    routePath: "M51.8 29.8 L58.5 30.6",
    ballFrom: [51.8, 53.2],
    ballTo: [58.5, 54.6],
    motion: {
      kind: "zip",
      mid: [55.2, 53.9],
      duration: 760,
      ease: "linear",
      scale: 0.96,
    },
    actors: [
      { playerId: "home-am10", role: "공 잃음", x: 51.0, y: 51.6, from: [48.0, 52.0], core: true, cardAnchor: "top", duration: 760 },
      { playerId: "away-dm8", role: "태클 성공", x: 55.8, y: 53.4, from: [58.0, 49.0], core: true, defenderCard: true, cardAnchor: "bottom", duration: 760 },
    ],
  },
  {
    id: "pass",
    type: "패스",
    badge: "PASS",
    time: "68:15",
    clock: "후반 68:15",
    score: [1, 1],
    subtitle: "숏패스: 완전 직선 이동, 수신자와 수비수도 짧게 반응",
    commentary: "AM-10이 ST-9 쪽으로 짧고 빠른 직선 패스를 넣습니다. 수신자는 공 쪽으로 한 걸음 움직입니다.",
    routePath: "M50.2 30.2 L66.3 28.2",
    ballFrom: [50.2, 54.0],
    ballTo: [66.3, 50.3],
    motion: {
      kind: "zip",
      mid: [58.25, 52.15],
      duration: 560,
      ease: "linear",
      scale: 0.95,
    },
    actors: [
      { playerId: "home-am10", role: "패스", x: 49.0, y: 53.4, from: [47.0, 53.8], core: true, cardAnchor: "bottom", duration: 560 },
      { playerId: "home-st9", role: "수신", x: 69.5, y: 49.2, from: [66.5, 49.8], core: true, cardAnchor: "top", duration: 560 },
      { playerId: "away-cb5", role: "라인 차단", x: 74.2, y: 45.4, from: [73.0, 44.2], core: false, duration: 560 },
    ],
  },
  {
    id: "cross",
    type: "크로스",
    badge: "CROSS",
    time: "71:00",
    clock: "후반 71:00",
    score: [1, 1],
    subtitle: "크로스 결과: 공격수 헤딩 연결",
    commentary: "WM-7이 직선에 가까운 크로스를 올리고, ST-9이 수비수와 겹치지 않는 낙하지점에서 헤딩으로 연결합니다.",
    routePath: "M62.5 43.4 L86.8 27.6",
    ballFrom: [62.5, 77.5],
    ballTo: [86.8, 49.2],
    motion: {
      kind: "aerial",
      mid: [74.65, 63.35],
      duration: 1420,
      ease: "linear",
      scale: 1.5,
    },
    actors: [
      { playerId: "home-wm7", role: "크로스", x: 60.4, y: 78.2, from: [59.2, 79.0], core: true, cardAnchor: "top", duration: 1420 },
      { playerId: "home-st9", role: "헤딩 연결", x: 85.0, y: 52.4, from: [80.8, 54.8], core: true, cardAnchor: "top", duration: 1420 },
      { playerId: "away-cb5", role: "경합", x: 89.8, y: 54.8, from: [90.5, 49.2], core: false, duration: 1420 },
      { playerId: "away-gk", role: "반응", x: 93.6, y: 49.4, from: [94.0, 50.0], core: false, keeper: true, duration: 1420 },
    ],
  },
  {
    id: "longpass",
    type: "롱패스",
    badge: "LONG PASS",
    time: "71:45",
    clock: "후반 71:45",
    score: [1, 1],
    subtitle: "롱패스: 방향 유지, 낙하지점 주변 바둑알 동시 반응",
    commentary: "CB-4가 전방으로 긴 패스를 보냅니다. ST-9이 낙하지점으로 움직이고 수비와 골키퍼도 함께 반응합니다.",
    routePath: "M35.8 33.8 L82.5 30.0",
    ballFrom: [35.8, 60.4],
    ballTo: [82.5, 53.5],
    motion: {
      kind: "aerial",
      mid: [59.15, 56.95],
      duration: 1680,
      ease: "linear",
      scale: 1.5,
    },
    actors: [
      { playerId: "home-cb4", role: "롱패스", x: 32.6, y: 61.4, from: [31.0, 62.0], core: true, cardAnchor: "bottom", duration: 1680 },
      { playerId: "home-st9", role: "낙하지점", x: 86.2, y: 52.0, from: [82.4, 53.5], core: true, cardAnchor: "top", duration: 1680 },
      { playerId: "away-cb5", role: "경합 수비", x: 90.3, y: 48.6, from: [90.6, 46.8], core: false, duration: 1680 },
      { playerId: "away-gk", role: "위치 조정", x: 95.0, y: 50.4, from: [94.0, 50.0], core: false, keeper: true, duration: 1680 },
    ],
  },
  {
    id: "shot",
    type: "슛",
    badge: "SHOT",
    time: "72:15",
    clock: "후반 72:15",
    score: [1, 1],
    subtitle: "슛: 슈터 발밑 바깥에서 골문으로 직선 이동",
    commentary: "ST-9이 바깥 발밑의 공을 골문 쪽으로 강하게 직선 슈팅합니다. 골키퍼가 즉시 반응합니다.",
    routePath: "M82 28.6 L97 27.2",
    ballFrom: [82.0, 51.1],
    ballTo: [97.0, 48.5],
    motion: {
      kind: "shot",
      mid: [89.5, 49.8],
      duration: 440,
      ease: "cubic-bezier(0.08, 0.86, 0.12, 1)",
      scale: 0.88,
    },
    actors: [
      { playerId: "home-st9", role: "슈팅", x: 78.6, y: 52.0, from: [76.5, 52.7], core: true, cardAnchor: "top", duration: 440 },
      { playerId: "away-cb5", role: "늦은 블록", x: 83.2, y: 46.5, from: [82.0, 45.5], core: false, duration: 440 },
      { playerId: "away-gk", role: "반응", x: 94.0, y: 51.3, from: [94.0, 50.0], core: true, keeper: true, defenderCard: true, cardAnchor: "bottom", duration: 440 },
    ],
  },
  {
    id: "goal",
    type: "골",
    badge: "GOAL",
    time: "78:00",
    clock: "후반 78:00",
    score: [2, 1],
    subtitle: "골: 슈팅 순간만 표시, 도움은 텍스트 정보로만 유지",
    commentary: "골! ST-9이 직선 슈팅으로 마무리합니다. 도움: AM-10.",
    routePath: "M80.8 29.2 L98.4 28.0",
    ballFrom: [80.8, 52.1],
    ballTo: [98.4, 50.0],
    motion: {
      kind: "shot",
      mid: [89.6, 51.05],
      duration: 500,
      ease: "cubic-bezier(0.1, 0.84, 0.16, 1)",
      scale: 0.86,
    },
    actors: [
      { playerId: "home-st9", role: "득점 슈팅", x: 77.4, y: 52.8, from: [75.8, 53.4], core: true, cardAnchor: "top", duration: 500 },
      { playerId: "away-cb5", role: "늦은 압박", x: 84.6, y: 48.0, from: [83.4, 47.0], core: false, duration: 500 },
      { playerId: "away-gk", role: "반응 실패", x: 95.0, y: 50.8, from: [94.0, 50.0], core: true, keeper: true, defenderCard: true, cardAnchor: "bottom", duration: 500 },
    ],
  },
];

const sampleStats = {
  possession: [54, 46],
  shots: [9, 6],
  shotsOnTarget: [4, 3],
  chances: [5, 3],
  saves: [2, 3],
  direction: { left: 23, middle: 49, right: 28 },
  momentum: [35, 52, 44, 66, 78, 58, 72, 49],
  playerStats: [
    { label: "ST-9", rating: "7.4", shots: 3, chances: 2, status: "득점" },
    { label: "AM-10", rating: "7.1", shots: 1, chances: 3, status: "어시스트" },
    { label: "GK-1", rating: "7.8", shots: 0, chances: 0, status: "선방 2" },
  ],
};

const sampleTactics = {
  name: "중앙 압박 후 빠른 전개",
  gauge: 72,
  sliders: [
    { label: "공격 성향", value: 68 },
    { label: "수비 라인", value: 56 },
    { label: "압박 강도", value: 74 },
    { label: "패스 성향", value: 42 },
  ],
  directions: ["중앙", "좌측", "우측", "롱볼"],
  activeDirection: "중앙",
  summary: [
    ["공격", "빠른 중앙 침투"],
    ["수비", "중간 라인 유지"],
    ["압박", "상대 빌드업 차단"],
  ],
  skills: [
    { name: "압박 강화", cooldown: "READY" },
    { name: "역습 지시", cooldown: "02:30" },
    { name: "집중 회복", cooldown: "05:10" },
    { name: "수비 정렬", cooldown: "READY" },
  ],
};

window.TFL_SAMPLE_DATA = {
  sampleMatchData,
  samplePlayers,
  sampleBenchPlayers,
  sampleEvents,
  sampleStats,
  sampleTactics,
};
